import Link from 'next/link';
import { getCoverUrl } from '@/lib/api';

interface MangaPageProps {
  params: {
      slug: string; // เช่น 'cutie'
        };
        }

        export default function MangaDetailPage({ params }: MangaPageProps) {
          const { slug } = params;
            
              [span_5](start_span)// จำลองข้อมูล (ในระบบจริงควรดึงจาก metadata.json หรือ API[span_5](end_span))
                const mangaInfo = {
                    title: slug === 'cutie' ? 'Cutie (มังงะทดสอบ)' : 'ชื่อมังงะ',
                        author: 'Moonshelf',
                            status: 'กำลังเผยแพร่',
                                [span_6](start_span)description: 'เรื่องย่อของมังงะเรื่องนี้... (สามารถดึงจาก description.txt ใน Nextcloud ได้[span_6](end_span))',
                                    genres: ['แฟนตาซี', 'โรแมนซ์'],
                                        [span_7](start_span)chapters: ['001', '002', '003'] // ดึงรายชื่อโฟลเดอร์ตอนย่อย[span_7](end_span)
                                          };

                                            return (
                                                <main className="wrap" style={{ paddingTop: '80px', paddingBottom: '80px' }}>
                                                      <div style={{ display: 'flex', gap: '40px', flexWrap: 'wrap' }}>
                                                              
                                                                      {/* ส่วนแสดงภาพปก */}
                                                                              <div style={{ flexShrink: 0, width: '300px' }}>
                                                                                        <div style={{ borderRadius: '12px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.5)' }}>
                                                                                                    <img 
                                                                                                                  src={getCoverUrl(slug)} 
                                                                                                                                alt={mangaInfo.title} 
                                                                                                                                              style={{ width: '100%', display: 'block' }}
                                                                                                                                                            // หากดึงรูปจาก Nextcloud ไม่ได้ จะแสดงพื้นหลังสีทึบแทน
                                                                                                                                                                          onError={(e) => (e.currentTarget.src = 'https://via.placeholder.com/300x450?text=No+Cover')}
                                                                                                                                                                                      />
                                                                                                                                                                                                </div>
                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                {/* ส่วนแสดงข้อมูล */}
                                                                                                                                                                                                                        <div style={{ flex: 1, minWidth: '300px' }}>
                                                                                                                                                                                                                                  <h1 style={{ fontSize: '42px', marginBottom: '10px', color: 'var(--moon)' }}>{mangaInfo.title}</h1>
                                                                                                                                                                                                                                            <p style={{ color: 'var(--cyan)', marginBottom: '20px' }}>แต่งโดย: {mangaInfo.author} | สถานะ: {mangaInfo.status}</p>
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                <div style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                            {mangaInfo.genres.map(genre => (
                                                                                                                                                                                                                                                                                          <span key={genre} style={{ padding: '6px 14px', background: 'var(--navy)', borderRadius: '20px', fontSize: '14px' }}>
                                                                                                                                                                                                                                                                                                          {genre}
                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                        <p style={{ color: 'var(--muted)', lineHeight: '1.8', marginBottom: '40px' }}>
                                                                                                                                                                                                                                                                                                                                                                    {mangaInfo.description}
                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                        <h3 style={{ fontSize: '24px', marginBottom: '20px', borderBottom: '1px solid var(--line)', paddingBottom: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                    รายชื่อตอน
                                                                                                                                                                                                                                                                                                                                                                                                              </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* สร้าง Component ลิสต์รายชื่อตอน */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {mangaInfo.chapters.map((chapter) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [span_8](start_span)href={`/read/${slug}/${chapter}`} // ลิงก์ไปยังหน้าอ่านตอน[span_8](end_span)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={chapter}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: 'flex', justifyContent: 'space-between', padding: '16px 20px', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: 'var(--navy)', borderRadius: '8px', border: '1px solid var(--line)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ fontWeight: 'bold' }}>ตอนที่ {chapter}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ color: 'var(--muted)', fontSize: '14px' }}>อ่านเลย →</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                