import { getMangaMetadata, getNextcloudUrl } from '@/lib/api';
import Link from 'next/link';

interface ReaderProps {
  params: {
      slug: string;
          chapter: string;
            };
            }

            export default async function ReaderPage({ params }: ReaderProps) {
              const { slug, chapter } = params;
                const mangas = await getMangaMetadata();
                  
                    // ค้นหาข้อมูลมังงะเรื่องปัจจุบัน
                      const currentManga = mangas.find((m: any) => m.slug === slug);
                        
                          // สมมติจำนวนหน้าเริ่มต้นที่ 30 หน้าต่อตอน (หรือตั้งค่าดึงจาก metadata ได้)
                            const maxPages = 30; 
                              const pages = Array.from({ length: maxPages }, (_, i) => String(i + 1).padStart(3, '0') + '.jpg');

                                return (
                                    <main style={{ background: '#05070d', minHeight: '100vh', paddingTop: '80px', paddingBottom: '100px' }}>
                                          <div className="wrap" style={{ maxWidth: '800px' }}>
                                                  
                                                          {/* ส่วนหัวหน้าอ่าน */}
                                                                  <div style={{ textAlign: 'center', marginBottom: '40px', color: 'var(--paper)' }}>
                                                                            <h2 style={{ color: 'var(--moon)', marginBottom: '10px' }}>{currentManga?.title || slug}</h2>
                                                                                      <p style={{ color: 'var(--cyan)' }}>บทที่ / ตอนที่: {chapter}</p>
                                                                                                <Link href={`/manga/${slug}`} style={{ color: 'var(--blue-bright)', fontSize: '14px', textDecoration: 'underline' }}>
                                                                                                            กลับไปหน้ารายชื่อตอน
                                                                                                                      </Link>
                                                                                                                              </div>

                                                                                                                                      {/* พื้นที่แสดงรูปภาพมังงะแบบ Scroll เลื่อนลงยาวๆ */}
                                                                                                                                              <div style={{ display: 'flex', flexDirection: 'column', gap: '0px', width: '100%', background: '#000', borderRadius: '8px', overflow: 'hidden' }}>
                                                                                                                                                        {pages.map((filename, index) => {
                                                                                                                                                                    // สร้าง Full Path ไปยังรูปภาพบน Nextcloud เช่น: /cutie/chapters/001/001.jpg
                                                                                                                                                                                const imagePath = `/${slug}/chapters/${chapter}/${filename}`;
                                                                                                                                                                                            const fullImageUrl = getNextcloudUrl(imagePath);

                                                                                                                                                                                                        return (
                                                                                                                                                                                                                      <div key={filename} style={{ width: '100%', position: 'relative' }}>
                                                                                                                                                                                                                                      <img 
                                                                                                                                                                                                                                                        src={fullImageUrl} 
                                                                                                                                                                                                                                                                          alt={`หน้า ${index + 1}`} 
                                                                                                                                                                                                                                                                                            style={{ width: '100%', height: 'auto', display: 'block' }}
                                                                                                                                                                                                                                                                                                              loading={index <= 2 ? "eager" : "lazy"} // 2 หน้าแรกโหลดทันที หน้าอื่นโหลดเมื่อเลื่อนถึง
                                                                                                                                                                                                                                                                                                                                onError={(e) => {
                                                                                                                                                                                                                                                                                                                                                    // หากรูปภาพหมดหน้าแล้ว (เช่น มีแค่ 12 หน้า แต่ลูปไป 30) จะซ่อน Element นั้นไปอัตโนมัติ
                                                                                                                                                                                                                                                                                                                                                                        e.currentTarget.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                              })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* ปุ่มควบคุมเปลี่ยนตอนด้านล่างสุด */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '40px', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href={`/manga/${slug}`} style={{ padding: '10px 20px', background: 'var(--navy)', border: '1px solid var(--line)', borderRadius: '6px', color: 'var(--moon)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ⬅ รายชื่อตอน
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ color: 'var(--muted)' }}>สิ้นสุดตอน</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    