// src/app/read/[slug]/[chapter]/page.tsx
import { getImageUrl } from '@/lib/nextcloud';
import Image from 'next/image';

interface Props {
  params: { slug: string; chapter: string };
  }

  export default function ReaderPage({ params }: Props) {
    const { slug, chapter } = params;

      // สร้างลิสต์หน้าตอน (สมมติ 20 หน้า)
        const totalPages = 20;
          const pages = Array.from({ length: totalPages }, (_, i) => i + 1);

            return (
                <div className="bg-black min-h-screen text-white">
                      {/* Reader Header */}
                            <header className="fixed top-0 left-0 right-0 z-50 bg-black/90 border-b border-gray-800 backdrop-blur-md">
                                    <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
                                              <div className="flex items-center gap-4">
                                                          <a href={`/manga/${slug}`} className="text-blue-400 hover:text-blue-300">
                                                                        ← กลับ
                                                                                    </a>
                                                                                                <div>
                                                                                                              <h1 className="font-bold">{slug.toUpperCase()} - ตอน {chapter}</h1>
                                                                                                                            <p className="text-sm text-gray-400">หน้า 1 / {totalPages}</p>
                                                                                                                                        </div>
                                                                                                                                                  </div>

                                                                                                                                                            <div className="flex items-center gap-6 text-sm">
                                                                                                                                                                        <button className="hover:text-blue-400">◀ Previous</button>
                                                                                                                                                                                    <button className="hover:text-blue-400">Next ▶</button>
                                                                                                                                                                                                <button className="bg-gray-800 px-4 py-1.5 rounded-lg">ตั้งค่า</button>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                        </header>

                                                                                                                                                                                                                              {/* Main Reader */}
                                                                                                                                                                                                                                    <main className="pt-20 pb-20 flex justify-center bg-black">
                                                                                                                                                                                                                                            <div className="max-w-4xl w-full px-4">
                                                                                                                                                                                                                                                      {pages.map((pageNum) => (
                                                                                                                                                                                                                                                                  <div key={pageNum} className="mb-8 flex justify-center">
                                                                                                                                                                                                                                                                                <Image
                                                                                                                                                                                                                                                                                                src={getImageUrl(slug, `\( {chapter.padStart(3, '0')}/ \){pageNum.toString().padStart(3, '0')}.jpg`)}
                                                                                                                                                                                                                                                                                                                alt={`Page ${pageNum}`}
                                                                                                                                                                                                                                                                                                                                width={800}
                                                                                                                                                                                                                                                                                                                                                height={1200}
                                                                                                                                                                                                                                                                                                                                                                className="rounded shadow-2xl"
                                                                                                                                                                                                                                                                                                                                                                                priority={pageNum <= 3}
                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Reader Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                              <footer className="fixed bottom-0 left-0 right-0 bg-black/90 border-t border-gray-800 py-4 z-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="max-w-5xl mx-auto px-6 flex justify-between items-center text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>ตอน {chapter} • หน้า 1/{totalPages}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="px-5 py-2 bg-gray-800 rounded-lg hover:bg-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ← ตอนก่อนหน้า
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="px-5 py-2 bg-blue-600 rounded-lg hover:bg-blue-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ตอนถัดไป →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }