import Link from 'next/link';
import { getMangaMetadata, getNextcloudUrl } from '@/lib/api';

export default async function HomePage() {
  // ดึงข้อมูล ซึ่งถ้าล่มจะได้ [] กลับมาแทน
    const mangas = await getMangaMetadata();

      return (
          <main style={{ paddingTop: '80px' }}>
                {/* HERO SECTION (ยังคงแสดงเหมือนเดิมให้เว็บดูสวยงาม) */}
                      <section className="hero" style={{ padding: '60px 0', position: 'relative' }}>
                              <div className="wrap">
                                        <div className="eyebrow" style={{ color: 'var(--cyan)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '10px' }}>
                                                    🌙 Reading Under The Moonlight
                                                              </div>
                                                                        <h1 style={{ fontSize: '3.5rem', color: 'var(--moon)', marginBottom: '20px', lineHeight: '1.2' }}>
                                                                                    อ่านมังงะเรื่องโปรด<br />ใต้แสง<em style={{ color: 'var(--blue-bright)', fontStyle: 'normal' }}>จันทร์</em>
                                                                                              </h1>
                                                                                                        <p style={{ color: 'var(--paper)', maxWidth: '600px', marginBottom: '30px', opacity: 0.8 }}>
                                                                                                                    ยินดีต้อนรับสู่ Moonshelf ชั้นหนังสือดิจิทัลส่วนตัวของคุณ เชื่อมต่อตรงกับระบบ Nextcloud Storage อัปเดตไว อ่านลื่นไหลไร้โฆษณาคั่น
                                                                                                                              </p>
                                                                                                                                      </div>
                                                                                                                                            </section>

                                                                                                                                                  {/* MANGA LIST SECTION */}
                                                                                                                                                        <section id="trending" style={{ padding: '40px 0' }}>
                                                                                                                                                                <div className="wrap">
                                                                                                                                                                          <h2 style={{ color: 'var(--moon)', marginBottom: '30px', borderBottom: '1px solid var(--line)', paddingBottom: '10px' }}>
                                                                                                                                                                                      มังงะทั้งหมดบนชั้นหนังสือ
                                                                                                                                                                                                </h2>
                                                                                                                                                                                                          
                                                                                                                                                                                                                    {/* เช็คว่ามีข้อมูลมังงะหรือไม่ */}
                                                                                                                                                                                                                              {mangas && mangas.length > 0 ? (
                                                                                                                                                                                                                                          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '30px' }}>
                                                                                                                                                                                                                                                        {mangas.map((manga: any) => (
                                                                                                                                                                                                                                                                        <Link href={`/manga/${manga.slug}`} key={manga.slug} style={{ display: 'block' }}>
                                                                                                                                                                                                                                                                                          <div style={{ background: 'var(--navy)', borderRadius: '12px', overflow: 'hidden', border: '1px solid var(--line)' }}>
                                                                                                                                                                                                                                                                                                              <div style={{ width: '100%', height: '300px', background: 'var(--navy-deep)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                                                                                                                                                                                                                                                                                                                    <img 
                                                                                                                                                                                                                                                                                                                                                            src={getNextcloudUrl(`/${manga.slug}/cover.jpg`)} 
                                                                                                                                                                                                                                                                                                                                                                                    alt={manga.title}
                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                    // ถ้ารูปโหลดไม่ขึ้น (Nextcloud ล่ม) ให้ซ่อนรูป แล้วปล่อยให้เห็นพื้นหลังสีทึบแทน
                                                                                                                                                                                                                                                                                                                                                                                                                                                            onError={(e) => { e.currentTarget.style.display = 'none'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ padding: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h4 style={{ color: 'var(--moon)', margin: '0 0 5px 0' }}>{manga.title}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: 'var(--muted)', fontSize: '13px' }}>{manga.author}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // หากดึงข้อมูลไม่ได้ ให้แสดงข้อความนี้แทนการปล่อยเว็บพัง
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ textAlign: 'center', padding: '60px 20px', background: 'var(--navy)', borderRadius: '12px', border: '1px dashed var(--line)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 style={{ color: 'var(--moon)', marginBottom: '10px' }}>📭 ยังไม่มีมังงะบนชั้นหนังสือ</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ color: 'var(--muted)' }}>ระบบไม่สามารถเชื่อมต่อกับคลังข้อมูลได้ในขณะนี้ หรือคุณยังไม่ได้อัปโหลดมังงะ</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              