import Link from 'next/link';
import { getMangaMetadata, getNextcloudUrl } from '@/lib/api';

export default async function HomePage() {
  const mangas = await getMangaMetadata();

    return (
        <main style={{ paddingTop: '80px' }}>
              {/* HERO SECTION */}
                    <section className="hero" style={{ padding: '60px 0', textPosition: 'relative' }}>
                            <div className="wrap">
                                      <div className="eyebrow" style={{ color: 'var(--cyan)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '10px' }}>
                                                  🌙 Reading Under The Moonlight
                                                            </div>
                                                                      <h1 style={{ fontSize: '3.5rem', color: 'var(--moon)', marginBottom: '20px', lineHeight: '1.2' }}>
                                                                                  อ่านมังงะเรื่องโปรด<br />ใต้แสง<em style={{ color: 'var(--blue-bright)', fontStyle: 'normal' }}>จันทร์</em>
                                                                                            </h1>
                                                                                                      <p style={{ color: 'var(--paper)', maxWidth: '600px', marginBottom: '30px', opacity: 0.8 }}>
                                                                                                                  ยินดีต้อนรับสู่ Moonshelf ชั้นหนังสือดิจิทัลส่วนตัวของคุณ เชื่อมต่อตรงกับระบบ Nextcloud Storage อัปเดตไว อ่านลื่นไหลไร้โฆษณาคั่น
                                                                                                                            </p>
                                                                                                                                    </div>
                                                                                                                                          </section>

                                                                                                                                                {/* MANGA LIST SECTION */}
                                                                                                                                                      <section id="trending" style={{ padding: '40px 0' }}>
                                                                                                                                                              <div className="wrap">
                                                                                                                                                                        <h2 style={{ color: 'var(--moon)', marginBottom: '30px', borderBottom: '1px solid var(--line)', paddingBottom: '10px' }}>
                                                                                                                                                                                    มังงะทั้งหมดบนชั้นหนังสือ
                                                                                                                                                                                              </h2>
                                                                                                                                                                                                        
                                                                                                                                                                                                                  <div style={{ 
                                                                                                                                                                                                                              display: 'grid', 
                                                                                                                                                                                                                                          gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', 
                                                                                                                                                                                                                                                      gap: '30px' 
                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                            {mangas.map((manga: any) => (
                                                                                                                                                                                                                                                                                          <Link href={`/manga/${manga.slug}`} key={manga.slug} className="card" style={{ group: 'true' }}>
                                                                                                                                                                                                                                                                                                          <div style={{ 
                                                                                                                                                                                                                                                                                                                            background: 'var(--navy)', 
                                                                                                                                                                                                                                                                                                                                              borderRadius: '12px', 
                                                                                                                                                                                                                                                                                                                                                                overflow: 'hidden', 
                                                                                                                                                                                                                                                                                                                                                                                  border: '1px solid var(--line)',
                                                                                                                                                                                                                                                                                                                                                                                                    transition: 'all 0.3s ease',
                                                                                                                                                                                                                                                                                                                                                                                                                      position: 'relative'
                                                                                                                                                                                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* แสดงปกเรื่องจาก Nextcloud */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ width: '100%', height: '300px', overflow: 'hidden', background: '#0b1120' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src={getNextcloudUrl(`/${manga.slug}/cover.jpg`)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt={manga.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onError={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ถ้าไม่มีรูปใน Nextcloud ให้ใช้ placeholder
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      e.currentTarget.src = 'https://via.placeholder.com/300x450?text=Moonshelf+Manga';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* ข้อมูลมังงะด้านล่างการ์ด */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ padding: '15px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h4 style={{ color: 'var(--moon)', margin: '0 0 5px 0', fontSize: '16px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {manga.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ color: 'var(--muted)', fontSize: '13px', margin: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {manga.author}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginTop: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontSize: '11px', background: 'var(--navy-light)', color: 'var(--cyan)', padding: '3px 8px', borderRadius: '4px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {manga.genres[0] || 'มังงะ'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          